name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Make debug build available for download
      uses: actions/upload-artifact@v3
      with: 
        name: debug-build
        path: app/build/outputs/apk/debug

    - name: Release debug builds as prerelease
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        token: ${{ secrets.TOKEN }}
        files: app/build/outputs/apk/debug/app-debug.apk
